service: helloer-service

provider:
  name: aws
  stage: dev-env
  runtime: python3.8
  region: eu-central-1

functions:
  helloer:
    handler: helloer.hello_handler
    events:
      - http:
          path: /hello
          method: GET
          cors: false

frameworkVersion: "^1.5.0"
