write_files:
- path: /etc/app/key
  permissions: '0600'
  content: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEAvWxCEQe1+3rPcF2KeFv5Owxmup0L5zWFNghdMO8O16o2V+Ia
    tE1FhM3MllMHiyuuhtD6iqvF9u+N30n7MUyLSb9W3AvvMphE/ayqxQD5HqKgkqtB
    8YSprmNHqT6xF+8VV/G3DtGu/im/7mMTRthW8LyDmAm3wR4CQZgHNkWcAMOOx0RZ
    R9SglduJ05UDAn8k64wsG/yYGepQu23PmdpYq+J7K/WOMO/ll3p9rST+qjkbsKTy
    VRHMT9YNACjo7xiY9Z/Bxm9FMsXYeZuBp9Tw6++n1sL9/05qrtILYV/LnsEFYUC/
    4sG1bWT4ilya4dC2UehcwNZms4Sq6KYAEhj4HQatnTWPyKLMXplJqxn3C0rYv4Kh
    yI3ScRk/8RkQorZCpuD74dRQaB+9+g5gFTbG5vYiWFX4cp6X61Ss5BWixyHnC1Uw
    cRGNgt1QTKgzRyYrAy4RyP+yvJ7Lquob8xYZWgS2ZYntDfsoYmUw3R3OI6fcY+Dg
    Qn1CdIcp/BlPcCxHjr2ozNKeDEcQSc9y426x88i4QypXb4D4jnNyLt1MBIDfyOaV
    By0EVc4UONFIOn5/93+8a9p2Yx7S21EA5fa537q5JKDwyrSwoSVjpJPiYhKi/xTN
    sGob+C8Gvg/qWSASqtCpEsBSPTFWYbvkzRP2Mc8L+sysSuleX6Z39jOnoDMCAwEA
    AQKCAgAc+zJEfsSGHG0eiQFFlvTT5vrUtHB8yICAGtl/QiQoNP+phIuHaIcpYX9a
    xItT7LQAJnseuldIh7BSKHSJP2fUObUlZ6IKQKfVlBRwncx/tmwQ5KjrNdvsNX5i
    U5guzEKcuPvEBarbcjHOXFQ3s6Pho0YS/fGiV2AK/yKjWBUdPM5ciIWMaujC5Nr6
    h0L1n9RbQZACHCx9Uo9VjeCEbpbAfZ9Qw3ok3J9pBLGzywQ3sRMefK4i+90hneNR
    UfEJm97TPcUdAis5MHIFcRhuQDM4Neuc/Sp1ZF8ILlTVah2yRV/4WDrDi9WhTiCE
    stRzlkY+0+lVC7ic4MBxZex+2FklfFy/tgupxWo3qpQVBQO1uWuirN0Xed0q5epP
    XOEmZxqa304hcId1ILyEbgzO7W/n0pBX9isZQPBvPHf9S5qQIjYOkAQf5KBXi1xW
    g6mh1GPghND/ltyIY+afCkFe+/OBy67kxd1pxxm9Jp7A7QpKvr4JDGMPUuCK8jNj
    glhyMQ141dJaxraE5ix2rbv4+DOGnMQetOtEjY28w8h1c8U9Pem8NU1Lsiyry3dR
    D5L+4TsoYxSCIc/glfOAkE7MpUy6qeLhWmqQLSfD2EcEdcUWrU5w2ZP2W9yeM5XY
    x/BvFOO5ADK9GGUviEeM95RqRPQ4ZhNqChq2MF/WU6KHmETDeQKCAQEA3Hk5o0r+
    gojIsVcI4PUMO59NoHwzMIkUSOWHq7Qfcvnvkxwri5dHqdLVfcAWbuzzVw9+w4o3
    M9G+RqssQqlvA58L7yWyXk1c/KBxMbi7rfM24SHrMX+MwmusEYhOyo4gCy2ldfGK
    GBIoCUnt3WwEA0zNIoxh3EmSHJF+B7da5g1S8XavBIXcLmaOXiYnfa0N4ro/JUmX
    fkTcEDik371OIo8k5RNpd6PPQp3Ol1+NKFld5R+Tg0DDjhyNohMqKcxH/s9EBVCH
    vil7m+6QDXdMTYVlMEk1U04JlB0xzAxbS85wCgF9CbFKxQtW5QzDKkVQRXuCLMli
    wUmjwvVPU/vSzQKCAQEA2/Io1GJ2Ge6+Z02cc0BF9LbGQDWOpp7y4iScW1lQbIrD
    +EstxzTpAI+vsdw/xsiIZ4oRCbXPeISOgl8d4dYx09Pp5krhm4a2IsOsLePfmAmD
    NoHrVyvGyhgtmLaJYIsa8xu4k/2RGVpJkPvOF4cstr6fVi8EmoqyZiUMYruiWKTa
    q4LbHb5uOKTpHNOLtXfRcMk0lC6QBHtQ7BdSRpwXIJTbR5oMoQT40X3ONWn6+IB6
    p3umNwpC6twtrBXen1HuRMWQ6vqMwUWIIwe8wTPMguKRv2z347EbGb/YqNZH1eFG
    I6vDsQEzcFMuMklS7BqYnPJ7ZOp7auUm04gVh88+/wKCAQEAuGIlovwAF/j/Jtjs
    Ev69KUvUJuhYAzpRHZngOegc+RIvmy9O96IgC9XIOC+iU0iVRfUuhagc/Jhn8kAL
    dwCuWC/2Uh2Lq7Q1lQ01PWkKhLLH7cZpJO9QL/TOZadChcIQ6GhXXWkQnYrpssMC
    TFCelofvcvpGiW155ayD4z4jpgv0lv4z5qtwddnNLM3p7wAAgeJTFwMR0EcUZ/iH
    Ypq2Ms7WA0KVzLnRhxvk/9GogtsiXJFo07chFMOqa6Ztd6FhgKekcnFj5NRajREZ
    pjlkNdzewGApWa8E8brsv4KCA8b1ClkuUiHUrzAJjut6eOqY9FMTjhMqJQ5KB60S
    l+Ed7QKCAQB8whFy1x7Set+5zQYvQYfs1TgC994gmQyARfACyNibmOKsFkizNEnu
    LZKlOp9abCkjQeeEMIKsg9QqEzXqAgtlclC8dkEebP0nHwKtTRJpNQwegPczDPvH
    aouCkhe+kWkJ+PFr0GrbjKEqAgrWwbAVQG80/ZqI5p9m3SD3aCMgUPJQUvtjFb+D
    ldc8qKoYlwxQA3E1lGvQfvpZ0Ki0sJlVu9nd9X2wYBebDNdI6QKYrpfkJHkVw1ZN
    zfKCKC2NBXY3wDEBeHkasAwWgq8IkA8zNr0hbff2SWFr66xDqLg6k3urhCSOZHX/
    As+zanAEyNlEPS7NAUxcR/sMBabg0CeVAoIBABpvQB+HrzY1x8MBDdH3jEVz14r+
    LFP8UZum89yc/kfSDEiMbc1pZkdyKd6kbXCaohREq6WRGPYn0r4EpX66QISRr4J6
    NDfNhQqbFTzX+HTHtBknGGDaYS+zBPmq2T3TTh+v1ybEA9bRfCQ2Pv18byY8KFYf
    3AiULebZLPHFzCm/WBRcdf739y6He7myMCM+sO8bxKyYN1ePL+CJaKHfXUIqKzyU
    b4ZUKompxgF7dvDMpFGAY2raBxG34WwHPM89KY1EqHdn+mR5jlLHbs+2WNEHS/KS
    3YC32wbmQpM3vjf5vtaWp89wFvcyZyCrAlfTMkAXXaQGyVH0BLOEHVoGKSg=
    -----END RSA PRIVATE KEY-----
    
- path: /etc/app/key.pub
  permissions: '0644'
  content: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvWxCEQe1+3rPcF2KeFv5
    Owxmup0L5zWFNghdMO8O16o2V+IatE1FhM3MllMHiyuuhtD6iqvF9u+N30n7MUyL
    Sb9W3AvvMphE/ayqxQD5HqKgkqtB8YSprmNHqT6xF+8VV/G3DtGu/im/7mMTRthW
    8LyDmAm3wR4CQZgHNkWcAMOOx0RZR9SglduJ05UDAn8k64wsG/yYGepQu23PmdpY
    q+J7K/WOMO/ll3p9rST+qjkbsKTyVRHMT9YNACjo7xiY9Z/Bxm9FMsXYeZuBp9Tw
    6++n1sL9/05qrtILYV/LnsEFYUC/4sG1bWT4ilya4dC2UehcwNZms4Sq6KYAEhj4
    HQatnTWPyKLMXplJqxn3C0rYv4KhyI3ScRk/8RkQorZCpuD74dRQaB+9+g5gFTbG
    5vYiWFX4cp6X61Ss5BWixyHnC1UwcRGNgt1QTKgzRyYrAy4RyP+yvJ7Lquob8xYZ
    WgS2ZYntDfsoYmUw3R3OI6fcY+DgQn1CdIcp/BlPcCxHjr2ozNKeDEcQSc9y426x
    88i4QypXb4D4jnNyLt1MBIDfyOaVBy0EVc4UONFIOn5/93+8a9p2Yx7S21EA5fa5
    37q5JKDwyrSwoSVjpJPiYhKi/xTNsGob+C8Gvg/qWSASqtCpEsBSPTFWYbvkzRP2
    Mc8L+sysSuleX6Z39jOnoDMCAwEAAQ==
    -----END PUBLIC KEY-----
    